### ISSUE TITLE
Upstream changes

### ISSUE THREAD

**Issue by Stebalien** [ipfs/bbloom#1]
We've made a bunch of changes that should be upstreamed. As it stands, we've diverged from upstream so we really *shouldn't* be using this library as a *replacement* for upstream (especially given our API changes).

**Comment by Artoria2e5** [comment]
The upstream has been archived with a notice that it has been moved here, so I assume this issue would be moot?

Oh right, there's also the upstream of the upstream...

**Comment by Stebalien** [comment]
At this point, I think we're just going to keep using the fork. The code here avoids unsafe entirely and I've gone through it many times to make sure it's safe.
